version: '3.7'
services:
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROXY_HOST=${PROXY_HOST}
    extra_hosts:
      - "host.docker.internal:host-gateway"
